apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
  labels:
    app: resultserver-deploy
spec:
  selector:
    app: resultserver-deploy
  ports:
  - port: 80
    targetPort: 
    protocol: TCP
    nodePort: 30002
  type: NodePort
