apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: izmiristanbul/206webserver
        name: 206webserver
        ports:
          - containerPort: 80
        env:
        # - name:  MYSQL_DATABASE
        #   value: phonebook
        # - name:  MYSQL_USER
        #   value: clarus
        # - name:  MYSQL_DATABASE_HOST
        #   value: mysql-service
        - name:  MYSQL_PASSWORD
          # value: Clarusway_1
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_admin_password
        envFrom:
          - configMapRef:
              name: server-configmap
        resources: {}
